/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Sign In */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GoogleAuthRequest"];
                };
            };
            responses: {
                /** @description Login Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid Google Token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Authenticated User */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout User */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardingRequest"];
                };
            };
            responses: {
                /** @description Onboarding Completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Validation Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description My Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description Updated Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description Validation Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public User Profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description User Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collaborations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collaboration Feed */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    category?: components["schemas"]["Category"];
                    lat?: number;
                    lng?: number;
                    radius?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collaboration Feed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollaborationFeedResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create Collaboration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCollaborationRequest"];
                };
            };
            responses: {
                /** @description Collaboration Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCollaborationResponse"];
                    };
                };
                /** @description Validation Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collaborations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collaboration Details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collaboration Details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollaborationResponse"];
                    };
                };
                /** @description Collaboration Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete Collaboration */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted Successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update Collaboration */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCollaborationRequest"];
                };
            };
            responses: {
                /** @description Updated Successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollaborationResponse"];
                    };
                };
                /** @description Only Creator Can Update */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/collaborations/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request To Join Collaboration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["JoinRequest"];
                };
            };
            responses: {
                /** @description Join Request Submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collaborations/{id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pending Join Requests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pending Requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: {
                                requestId?: string;
                                joinMessage?: string;
                                status?: components["schemas"]["JoinStatus"];
                                user?: components["schemas"]["User"];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collaborations/{id}/requests/{requestId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Join Request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Request Approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collaborations/{id}/requests/{requestId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Join Request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Request Rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collaborations/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave Collaboration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Left Collaboration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Chat Rooms */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chat Rooms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatRoomsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/rooms/{roomId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room Messages */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessagesResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Send Message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description Message Sent */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit User Rating */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitRatingRequest"];
                };
            };
            responses: {
                /** @description Rating Submitted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Invalid Rating */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cannot Rate User */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notifications */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Notification Read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification Marked Read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark All Notifications Read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All Notifications Read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            success: boolean;
            /** @example Unauthorized */
            message: string;
        };
        SuccessResponse: {
            /** @example true */
            success: boolean;
            /** @example Operation successful */
            message?: string;
        };
        PaginationMeta: {
            /** @example 1 */
            page?: number;
            /** @example 20 */
            limit?: number;
            /** @example 145 */
            total?: number;
            /** @example true */
            hasMore?: boolean;
        };
        AuthMeResponse: {
            success?: boolean;
            user?: {
                /** Format: uuid */
                id?: string;
                email?: string;
                name?: string;
                username?: string | null;
                avatarUrl?: string | null;
                onboardingCompleted?: boolean;
            };
        };
        ProfileResponse: {
            /** @example true */
            success: boolean;
            user: {
                /** Format: uuid */
                id: string;
                /** @example Rahul Sharma */
                name: string;
                /** @example rahul_23 */
                username: string;
                /** @example https://example.com/avatar.jpg */
                avatarUrl?: string | null;
                /** @example Traveller and football enthusiast */
                bio?: string | null;
                /**
                 * @example [
                 *       "TRIPS",
                 *       "SPORTS",
                 *       "EVENTS"
                 *     ]
                 */
                categories: components["schemas"]["Category"][];
            };
            stats: {
                /** @example 5 */
                created: number;
                /** @example 17 */
                joined: number;
                /** @example 10 */
                completed: number;
            };
            rating: {
                /**
                 * Format: float
                 * @description Average of all four rating categories rounded to 2 decimal places
                 * @example 3.08
                 */
                overall: number;
                /**
                 * Format: float
                 * @example 4.8
                 */
                showUpRating: number;
                /**
                 * Format: float
                 * @example 2.2
                 */
                friendlyRating: number;
                /**
                 * Format: float
                 * @example 1.2
                 */
                safeRating: number;
                /**
                 * Format: float
                 * @example 4.1
                 */
                collaborativeRating: number;
                /** @example 23 */
                totalReviews: number;
            };
        };
        PendingJoinRequestsResponse: {
            success?: boolean;
            data?: {
                requestId?: string;
                joinMessage?: string;
                status?: components["schemas"]["JoinStatus"];
                user?: {
                    id?: string;
                    name?: string;
                    username?: string;
                    avatarUrl?: string | null;
                };
            }[];
        };
        /** @enum {string} */
        Category: "CARPOOLING" | "EVENTS" | "STUDY" | "PROFESSIONAL" | "SPORTS" | "TRIPS" | "OTHER";
        /** @enum {string} */
        CollaborationStatus: "OPEN" | "FULL" | "COMPLETED" | "CANCELLED";
        /** @enum {string} */
        JoinStatus: "PENDING" | "APPROVED" | "REJECTED" | "LEFT";
        User: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            onboardingCompleted?: boolean;
            username?: string;
            avatarUrl?: string | null;
            bio?: string | null;
        };
        UserStats: {
            created?: number;
            joined?: number;
            completed?: number;
        };
        Location: {
            name: string;
            lat: number;
            lng: number;
        };
        Collaboration: {
            id?: string;
            category?: components["schemas"]["Category"];
            title?: string;
            description?: string;
            fromLocation?: components["schemas"]["Location"];
            toLocation?: components["schemas"]["Location"];
            /** Format: date-time */
            scheduledAt?: string;
            maxMembers?: number;
            status?: components["schemas"]["CollaborationStatus"];
            creator?: components["schemas"]["User"];
        };
        CollaborationFeedItem: {
            id?: string;
            category?: components["schemas"]["Category"];
            title?: string;
            description?: string;
            /** Format: date-time */
            scheduledAt?: string;
            status?: components["schemas"]["CollaborationStatus"];
            currentMembers?: number;
            maxMembers?: number;
            distanceMeters?: number | null;
            creator?: components["schemas"]["User"];
            fromLocation?: components["schemas"]["Location"];
            toLocation?: components["schemas"]["Location"];
        };
        ChatRoom: {
            roomId?: string;
            collaborationId?: string;
            title?: string;
            unreadCount?: number;
            lastMessage?: string;
        };
        Message: {
            id?: string;
            message?: string;
            /** Format: date-time */
            createdAt?: string;
            sender?: components["schemas"]["User"];
        };
        Notification: {
            id?: string;
            type?: string;
            title?: string;
            body?: string;
            isRead?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        GoogleAuthRequest: {
            idToken: string;
        };
        OnboardingRequest: {
            username: string;
            bio?: string;
            categories: components["schemas"]["Category"][];
        };
        UpdateProfileRequest: {
            username?: string;
            bio?: string;
            categories?: components["schemas"]["Category"][];
        };
        CreateCollaborationRequest: {
            category: components["schemas"]["Category"];
            title: string;
            description: string;
            fromLocation: components["schemas"]["Location"];
            toLocation: components["schemas"]["Location"];
            /** Format: date-time */
            scheduledAt: string;
            maxMembers: number;
        };
        UpdateCollaborationRequest: {
            title?: string;
            description?: string;
            /** Format: date-time */
            scheduledAt?: string;
            maxMembers?: number;
        };
        JoinRequest: {
            /** @example Interested in joining */
            message?: string;
        };
        SendMessageRequest: {
            message: string;
        };
        SubmitRatingRequest: {
            collaborationId: string;
            reviewedUserId: string;
            showUpRating: number;
            friendlyRating: number;
            safeRating: number;
            collaborativeRating: number;
            comment?: string;
        };
        AuthResponse: {
            success?: boolean;
            user?: components["schemas"]["User"];
        };
        UserProfileResponse: {
            success?: boolean;
            user?: components["schemas"]["User"];
            stats?: components["schemas"]["UserStats"];
        };
        CreateCollaborationResponse: {
            success?: boolean;
            /** Format: uuid */
            collaborationId?: string;
            chatRoomId?: string;
        };
        CollaborationResponse: {
            success?: boolean;
            collaboration?: components["schemas"]["Collaboration"];
            members?: {
                id?: string;
                name?: string;
                username?: string;
                avatarUrl?: string | null;
            }[];
            currentMembers?: number;
            isCreator?: boolean;
            myJoinStatus?: components["schemas"]["JoinStatus"];
        };
        CollaborationFeedResponse: {
            success?: boolean;
            data?: components["schemas"]["CollaborationFeedItem"][];
            pagination?: components["schemas"]["PaginationMeta"];
        };
        ChatRoomsResponse: {
            success?: boolean;
            data?: components["schemas"]["ChatRoom"][];
        };
        MessagesResponse: {
            success?: boolean;
            data?: components["schemas"]["Message"][];
        };
        NotificationsResponse: {
            success?: boolean;
            data?: components["schemas"]["Notification"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
